version: '3'
services:
  devops:
    image: akhiladocker23/devopsreponit:latest
    ports:
      - "85:80"
    volumes:
      - "devopsvol"
    deploy:
      replicas: 3

  aws:
    image: akhiladocker23/awsreponit:latest
    ports:
      - "86:80"
    volumes:
      - "awsvol"
    deploy:
      replicas: 3

  datascience:
    image: akhiladocker23/datasciencereponit:latest
    ports:
      - "87:80"
    volumes:
      - "datasciencevol"
    deploy:
      replicas: 3

  azure:
    image: akhiladocker23/azurereponit:latest
    ports:
      - "88:80"
    volumes:
      - "azurevol"
    deploy:
      replicas: 3
